version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./services/frontend
    ports:
      - 8080:8080
  backend:
    container_name: backend
    build: ./services/backend
    ports: 
      - 5000:5000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000